"""
W3 -- Manuscript table for the fold-wise normalisation correction.

Answers Reviewer #3, point 3.

Presentation problem this solves: the main accuracy table reports five seeds per
cell under cohort-wide normalisation. The corrected fold-wise runs exist for one
seed so far, and only for the two splits that have a leakage channel. Silently
swapping one seed into a five-seed table would misrepresent the evidence, and
leaving the uncorrected numbers as the paper's only accuracy table would be
worse.

So the main table keeps the five-seed numbers, clearly labelled as the
cohort-wide scheme, and this companion table reports the paired correction with
its seed count stated. The text says which is which.

Usage:
    python revision/scripts/foldwise_table.py
Outputs:
    tables/tab_foldwise_correction.tex
    outputs/foldwise_correction.md
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASE = Path(__file__).resolve().parents[1]
OUT = BASE / "outputs"
TAB = BASE / "tables"
OUT.mkdir(parents=True, exist_ok=True)
TAB.mkdir(parents=True, exist_ok=True)

MODELS = ["pathxdrp", "drpreter", "graphdrp", "cdrscan"]
PRETTY = {"pathxdrp": "PathXDRP", "drpreter": "DRPreter",
          "graphdrp": "GraphDRP", "cdrscan": "CDRScan"}
ENCODER = {
    "pathxdrp": "KEGG pathway statistics",
    "drpreter": "KEGG pathway statistics",
    "graphdrp": "1D-CNN over raw genes",
    "cdrscan": "expression MLP $+$ fingerprint",
}
SPLITS = [("cell_blind", "cell-blind"), ("tissue_blind", "tissue-blind")]


def pcc(model: str, split: str, tag: str = "") -> float | None:
    suf = f"_{tag}" if tag else ""
    f = ROOT / "results" / model / f"{split}_seed0_fold0{suf}.json"
    if not f.exists():
        return None
    return json.loads(f.read_text())["test"]["PCC"]


def main() -> None:
    data = {}
    for split, _ in SPLITS:
        for m in MODELS:
            a, b = pcc(m, split), pcc(m, split, "fw")
            if a is not None:
                data[(split, m)] = (a, b)

    L = [r"% Generated by revision/scripts/foldwise_table.py",
         r"\begin{table}[!h]", r"\centering\small",
         r"\caption{Effect of correcting the expression normalisation, on the",
         r"two splits that hold out cell lines and therefore have a leakage",
         r"channel. Paired runs, seed~0, identical in every respect except that",
         r"the per-gene moments are fitted on the fold's training cell lines",
         r"rather than on the full cohort. The other three splits place every",
         r"test cell line in training as well and are unaffected (verified to",
         r"four decimal places in Section~\ref{sec:methods:data}). The cell",
         r"encoder is listed for reference only; we found no consistent relation",
         r"between it and the size of the correction.}",
         r"\label{tab:foldwise_correction}",
         r"\begin{tabular*}{\columnwidth}{@{\extracolsep{\fill}}l l rr r@{}}",
         r"\toprule",
         r"\textbf{Split} & \textbf{Model (cell encoder)} & \textbf{cohort} & "
         r"\textbf{fold-wise} & $\boldsymbol{\Delta}$ \\",
         r"\midrule"]

    md = ["# Fold-wise normalisation: paired correction (seed 0)\n",
          "| Split | Model | Cell encoder | cohort | fold-wise | delta |",
          "|---|---|---|---|---|---|"]

    for si, (split, label) in enumerate(SPLITS):
        rows_here = [(m, data.get((split, m))) for m in MODELS]
        rows_here = [(m, v) for m, v in rows_here if v]
        for i, (m, (a, b)) in enumerate(rows_here):
            first = rf"\multirow{{{len(rows_here)}}}{{*}}{{{label}}}" if i == 0 else ""
            if b is None:
                L.append(f"{first} & {PRETTY[m]} \\, {{\\footnotesize({ENCODER[m]})}} "
                         f"& ${a:.4f}$ & \\emph{{pending}} & -- \\\\")
                md.append(f"| {label} | {PRETTY[m]} | {ENCODER[m]} | {a:.4f} | pending | -- |")
                continue
            d = b - a
            bold = abs(d) > 0.01
            ds = (r"$\mathbf{" + f"{d:+.4f}" + "}$") if bold else f"${d:+.4f}$"
            L.append(f"{first} & {PRETTY[m]} \\, {{\\footnotesize({ENCODER[m]})}} "
                     f"& ${a:.4f}$ & ${b:.4f}$ & {ds} \\\\")
            md.append(f"| {label} | {PRETTY[m]} | {ENCODER[m]} | {a:.4f} | "
                      f"{b:.4f} | **{d:+.4f}**" if bold else
                      f"| {label} | {PRETTY[m]} | {ENCODER[m]} | {a:.4f} | {b:.4f} | {d:+.4f} |")
        if si < len(SPLITS) - 1:
            L.append(r"\addlinespace")

    L += [r"\bottomrule", r"\end{tabular*}", "",
          r"\smallskip",
          r"\footnotesize\emph{Note:} Single seed per cell, against the five",
          r"seeds behind Table~\ref{tab:pred}; the deltas are reported as a",
          r"paired correction rather than as replacement estimates. GraphDRP's",
          r"seed-to-seed standard deviation on cell-blind is $0.0014$, so its",
          r"$-0.016$ is roughly twelve standard deviations and is not seed",
          r"noise.",
          r"\end{table}"]

    TAB.joinpath("tab_foldwise_correction.tex").write_text("\n".join(L), encoding="utf-8")
    (OUT / "foldwise_correction.md").write_text("\n".join(md) + "\n", encoding="utf-8")
    print("\n".join(md))
    print(f"\nwrote {TAB/'tab_foldwise_correction.tex'}")


if __name__ == "__main__":
    main()
