"""
Cross-platform PRISM comparison, regenerated from the public download.

The PRISM numbers in the submitted version came from a sweep whose per-pair
predictions were not retained, so they could not be recomputed from the
release. This rebuilds the comparison for every model from
results/external/, which scripts/external_validation.py writes after
scripts/prepare_prism.py has assembled the response table from the public
Repurposing 20Q2 secondary screen.

Every model is evaluated on the same pairs: the drugs shared by name with
GDSC2, restricted to PRISM cell lines absent from the GDSC2 training cohort,
with implausible curve fits removed by an IQR x3 fence.

Usage:
    python revision/scripts/prism_table.py
Outputs:
    tables/tab_prism_external.tex
    outputs/prism_external.md
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

BASE = Path(__file__).resolve().parents[1]
ROOT = BASE.parent
OUT = BASE / "outputs"
TAB = BASE / "tables"
EXT = ROOT / "results" / "external"
OUT.mkdir(parents=True, exist_ok=True)
TAB.mkdir(parents=True, exist_ok=True)

MODELS = ["pathxdrp", "graphdrp", "drpreter", "cdrscan", "deepcdr"]
PRETTY = {"pathxdrp": "PathXDRP", "graphdrp": "GraphDRP",
          "drpreter": "DRPreter", "cdrscan": "CDRScan", "deepcdr": "DeepCDR"}
PREFIX = "prismNC"


def load(model: str) -> dict | None:
    """Metrics for one model, from whichever checkpoint was evaluated."""
    for stem in (f"{PREFIX}_random_seed0_fold0.json",
                 f"{PREFIX}_random_seed0_fold0_fw.json"):
        f = EXT / stem
        if not f.exists():
            continue
        rec = json.loads(f.read_text(encoding="utf-8"))
        if rec.get("args", {}).get("model", "pathxdrp") == model:
            return rec["test"]
    # per-model prediction files disambiguate when several share a stem
    for f in sorted(EXT.glob(f"{PREFIX}_*.json")):
        rec = json.loads(f.read_text(encoding="utf-8"))
        if rec.get("args", {}).get("model") == model:
            return rec["test"]
    return None


def main() -> None:
    rows = []
    for m in MODELS:
        t = load(m)
        if t is None:
            continue
        rows.append({"model": m, "PCC": t["PCC"], "Spearman": t["Spearman"],
                     "RMSE": t["RMSE"], "R2": t["R2"],
                     "per_drug": t.get("Per-drug PCC", np.nan),
                     "n": t["n_pairs"]})
    if not rows:
        print("no PRISM results found in", EXT)
        return

    df = pd.DataFrame(rows)
    df.to_csv(OUT / "prism_external.csv", index=False)

    best = df.loc[df.PCC.idxmax(), "model"]
    lo, hi = df.PCC.min(), df.PCC.max()

    L = ["# Cross-platform transfer to PRISM\n",
         "Regenerated from the public PRISM Repurposing 20Q2 secondary screen "
         "by `scripts/prepare_prism.py` and `scripts/external_validation.py`. "
         "Every model sees the same pairs: drugs shared by name with GDSC2, "
         "PRISM cell lines absent from the GDSC2 training cohort, implausible "
         "curve fits removed by an IQR x3 fence.\n",
         "| Model | PCC | Spearman | RMSE | R2_res | per-drug PCC | n |",
         "|---|---|---|---|---|---|---|"]
    for _, r in df.sort_values("PCC", ascending=False).iterrows():
        L.append(f"| {PRETTY[r.model]} | {r.PCC:.4f} | {r.Spearman:.4f} | "
                 f"{r.RMSE:.3f} | {r.R2:.3f} | {r.per_drug:.4f} | "
                 f"{int(r.n):,} |")
    L += ["", "## Reading", "",
          f"All {len(df)} architectures transfer into a PCC band of "
          f"{lo:.3f} to {hi:.3f}, a spread of {hi - lo:.3f}. "
          f"{PRETTY[best]} is nominally best. No architecture distinguishes "
          "itself, and the ordering here should not be read as a ranking: the "
          "band is narrower than the seed-to-seed spread within several of the "
          "GDSC2 blind splits.",
          "",
          "The residual coefficient of determination is negative for every "
          "model, which is the platform offset rather than a failure to "
          "discriminate; see the decomposition in the manuscript.",
          ""]
    (OUT / "prism_external.md").write_text("\n".join(L) + "\n", encoding="utf-8")

    T = [r"% Generated by revision/scripts/prism_table.py",
         r"\begin{table}[!ht]", r"\centering\small",
         r"\caption{Cross-platform transfer to the PRISM Repurposing "
         r"secondary screen, regenerated from the public release. Every model "
         r"is evaluated on the same held-out pairs: drugs shared by name with "
         r"GDSC2, restricted to PRISM cell lines absent from the GDSC2 "
         r"training cohort, with implausible dose-response fits removed by an "
         r"IQR$\times3$ fence. \Rres\ is negative for every model because the "
         r"two assays place \lnicfifty\ on scales separated by an offset; the "
         r"decomposition in the text shows it turns positive once the offset "
         r"is removed. Correlation is the answerable question under that "
         r"shift.}",
         r"\label{tab:prism_external}",
         r"\begin{tabular*}{\columnwidth}{@{\extracolsep{\fill}}lrrrrr@{}}",
         r"\toprule",
         r"\textbf{Model} & \textbf{PCC} & \textbf{Spearman} & "
         r"\textbf{RMSE} & \textbf{\Rres} & \textbf{per-drug} \\",
         r"\midrule"]
    for _, r in df.sort_values("PCC", ascending=False).iterrows():
        name = PRETTY[r.model]
        pcc = f"${r.PCC:.3f}$"
        if r.model == best:
            pcc = f"$\\mathbf{{{r.PCC:.3f}}}$"
        T.append(f"{name} & {pcc} & ${r.Spearman:.3f}$ & ${r.RMSE:.3f}$ & "
                 f"${r.R2:.3f}$ & ${r.per_drug:.3f}$ \\\\")
    T += [r"\bottomrule", r"\end{tabular*}", r"\end{table}", ""]
    (TAB / "tab_prism_external.tex").write_text("\n".join(T), encoding="utf-8")

    print("\n".join(L))
    print(f"wrote {TAB / 'tab_prism_external.tex'}")


if __name__ == "__main__":
    main()
